services:
  # ============================================
  # PostgreSQL Database
  # ============================================
  postgres:
    image: postgres:16-alpine
    container_name: logistics_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistics_system
      POSTGRES_INITDB_ARGS: "-U admin"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - logistics-network

  db-migration:
    build:
      context: .
      dockerfile: db-migration/Dockerfile
    container_name: db-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logistics_system
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      APP_DB_MIGRATION_ENABLED: "true"
    networks:
      - logistics-network
    restart: no
    profiles:
      - ""
  # ============================================
  # User Auth Service
  # ============================================
  user-auth-service:
    build:
      context: .                                # Контекст = корневая папка!
      dockerfile: user-auth-service/Dockerfile # Dockerfile внутри папки
    container_name: user-auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logistics_system
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db-migration
    networks:
      - logistics-network
    restart: unless-stopped

  # ============================================
  # Waybill Service (будущее)
  # ============================================
  # waybill-service:
  #   build:
  #     context: .
  #     dockerfile: waybill-service/Dockerfile
  #   container_name: waybill-service
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logistics_dev
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     SPRING_PROFILES_ACTIVE: dev
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - logistics-network

volumes:
  postgres_data:

networks:
  logistics-network:
    driver: bridge