apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "filebeat-*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: log.level
      interval: Daily
      timeInterval: "10s"
      maxConcurrentShardRequests: 5
    isDefault: true
    editable: true
